# Generated by Django 4.1.7 on 2023-03-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('icon', models.ImageField(upload_to='home/icon/', verbose_name='Иконка')),
                ('facebook', models.CharField(max_length=100, verbose_name='Ссылка на Фейсбук')),
                ('twitter', models.CharField(max_length=100, verbose_name='Ссылка на Твиттер')),
                ('youtube', models.CharField(max_length=100, verbose_name='Ссылка на Ютуб')),
                ('instagram', models.CharField(max_length=100, verbose_name='Ссылка на Инстарам')),
                ('linkedin', models.CharField(max_length=100, verbose_name='Ссылка на Линкедин')),
                ('active', models.BooleanField(default=False, verbose_name='Активировать')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('banner', models.ImageField(upload_to='home/banner/', verbose_name='Баннер')),
                ('active', models.BooleanField(default=False, verbose_name='Активировать')),
            ],
            options={
                'verbose_name': 'Основной Баннер',
                'verbose_name_plural': 'Основные Баннеры',
            },
        ),
    ]
