# Generated by Django 4.1.7 on 2023-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_settingmain_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmain',
            name='description',
            field=models.TextField(default=1, max_length=700, verbose_name='Описание Сайта'),
            preserve_default=False,
        ),
    ]
