# Generated by Django 4.1.7 on 2023-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_settingmain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmain',
            name='link_video',
            field=models.CharField(default=1, max_length=100, verbose_name='Ссылка на Видео'),
            preserve_default=False,
        ),
    ]
