# Generated by Django 4.1.7 on 2023-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(max_length=254, verbose_name='Первый Емаил')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Второй Емаил')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Третий Емаил')),
                ('phone1', models.CharField(max_length=20, verbose_name='Первый номер')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Второй номер')),
                ('phone3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Третий номер')),
                ('location', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
