# Generated by Django 4.1.7 on 2023-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил')),
                ('comments', models.TextField(max_length=1000, verbose_name='Ваше сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение Контакта',
                'verbose_name_plural': 'Сообщение из Контактов',
            },
        ),
    ]
