# Generated by Django 4.1.7 on 2023-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link_google_map',
            field=models.CharField(blank=True, help_text='<iframe...', max_length=100, null=True, verbose_name='Ссылка адресса из Google Maps'),
        ),
    ]
