# Generated by Django 4.1.7 on 2023-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_link_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link_google_map',
            field=models.CharField(blank=True, help_text='<iframe...', max_length=1000, null=True, verbose_name='Ссылка адресса из Google Maps'),
        ),
    ]
