# Generated by Django 4.1.7 on 2023-03-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/img/', verbose_name='Фото о нас')),
                ('title', models.CharField(max_length=100, verbose_name='Название о нас')),
                ('one_fact', models.CharField(max_length=80, verbose_name='Один факт о нас')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('first_plus', models.CharField(max_length=50, verbose_name='Первый плюс')),
                ('first_plus_desc', models.CharField(max_length=200, verbose_name='Описание первого плюса')),
                ('second_plus', models.CharField(max_length=50, verbose_name='Второй плюс')),
                ('second_plus_desc', models.CharField(max_length=200, verbose_name='Описание второго плюса')),
                ('third_plus', models.CharField(max_length=50, verbose_name='Третий плюс')),
                ('third_plus_desc', models.CharField(max_length=200, verbose_name='Описание третьего плюса')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='PartnersAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners_image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutpage.aboutus')),
            ],
            options={
                'verbose_name': 'Лого Партнера',
                'verbose_name_plural': 'Лого партнеров',
            },
        ),
    ]
