# Generated by Django 4.1.7 on 2023-03-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/author/', verbose_name='Фото')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('bio', models.TextField(verbose_name='Био')),
                ('facebook', models.CharField(max_length=100, verbose_name='Ссылка на Фейсбук')),
                ('google_link', models.CharField(max_length=100, verbose_name='Ссылка на Гугл почту')),
                ('twitter', models.CharField(max_length=100, verbose_name='Ссылка на Твиттер')),
                ('instagram', models.CharField(max_length=100, verbose_name='Ссылка на Инстаграмм')),
                ('pinteres', models.CharField(max_length=100, verbose_name='Ссылка на Пинтерес')),
            ],
            options={
                'verbose_name': 'Наш Автор',
                'verbose_name_plural': 'Наши Авторы',
            },
        ),
    ]
