# Generated by Django 4.1.7 on 2023-03-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideProffesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название Профессии')),
            ],
            options={
                'verbose_name': 'Профессия гида',
                'verbose_name_plural': 'Профессия гидов',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('bio', models.CharField(max_length=600, verbose_name='Коротко о себе')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на фейсбук')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на Твиттер')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на Инстаграмм')),
                ('youtube', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на Ютуб')),
                ('proffesion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='toueguide.guideproffesion', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гиды',
            },
        ),
    ]
