# Generated by Django 4.1.7 on 2023-03-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=60, verbose_name='Полное Имя')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Биография')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Емаил Почта')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password1', models.CharField(max_length=80)),
                ('password2', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
