# Generated by Django 4.1.7 on 2023-06-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
