# Generated by Django 4.1.7 on 2023-03-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='ExcludePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название исключении проездки')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='IncludePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название включении проездки')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='ItineraryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='DAY 1 - ....', max_length=100, verbose_name='Марштрут')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Название')),
                ('raiting_num', models.IntegerField(max_length=5, verbose_name='Рейтинг')),
                ('price_per_person', models.PositiveSmallIntegerField(verbose_name='Цена на одного человека')),
                ('days', models.IntegerField(max_length=30, verbose_name='Длительность дней')),
                ('nights', models.IntegerField(max_length=29, verbose_name='Длительность ночей')),
                ('max_person', models.IntegerField(verbose_name='Максимальное количество людей')),
                ('travel_country', models.CharField(max_length=50, verbose_name='Страна поездки')),
                ('image', models.ImageField(upload_to='package/', verbose_name='Фото')),
                ('overview', models.TextField(max_length=1000, verbose_name='Обзор')),
                ('itinerary_desc', models.TextField(max_length=300, verbose_name='Описание Маршрута')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='packages.categorypackage')),
                ('exclude', models.ManyToManyField(to='packages.excludepackage', verbose_name='Исключения в поездке')),
                ('include', models.ManyToManyField(to='packages.includepackage', verbose_name='Включения в поездке')),
                ('itinerary', models.ManyToManyField(to='packages.itinerarypackage', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
    ]
