# Generated by Django 4.1.7 on 2023-03-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_raiting_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypackage',
            options={'verbose_name': 'Категория Пакет', 'verbose_name_plural': 'Категория Пакетов'},
        ),
        migrations.AlterModelOptions(
            name='excludepackage',
            options={'verbose_name': 'Исключения в Пакет', 'verbose_name_plural': 'Исключения в Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='includepackage',
            options={'verbose_name': 'Включения в Пакет', 'verbose_name_plural': 'Включения в Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='itinerarypackage',
            options={'verbose_name': 'Маршрут Пакет', 'verbose_name_plural': 'Маршрут Пакетов'},
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='packages.categorypackage', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='package',
            name='days',
            field=models.IntegerField(verbose_name='Длительность дней'),
        ),
        migrations.AlterField(
            model_name='package',
            name='nights',
            field=models.IntegerField(verbose_name='Длительность ночей'),
        ),
        migrations.AlterField(
            model_name='package',
            name='raiting_num',
            field=models.IntegerField(default=0, help_text='Оценка от 1 до 5', verbose_name='Рейтинг'),
        ),
    ]
