# Generated by Django 4.1.7 on 2023-03-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_categorypackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент для действии акции'),
        ),
    ]
