# Generated by Django 4.1.7 on 2023-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_package_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='activate_promo',
            field=models.BooleanField(default=False, verbose_name='Активация акции'),
        ),
    ]
