# Generated by Django 4.1.7 on 2023-03-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_bookingformpackage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingFormPackage',
        ),
    ]
