# Generated by Django 4.1.7 on 2023-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='travel_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна поездки'),
        ),
    ]
