# Generated by Django 4.1.7 on 2023-06-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_package_travel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.country'),
        ),
    ]
