# Generated by Django 4.1.7 on 2023-06-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_raiting_num'),
        ('packages', '0013_package_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination', verbose_name='Пункт названачения'),
        ),
    ]
