# Generated by Django 4.1.7 on 2023-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('NA', 'Not in Action'), ('PR', 'Progress'), ('FN', 'Finish')], default='NA', max_length=2, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
