# Generated by Django 4.1.7 on 2023-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='raiting_num',
            field=models.IntegerField(default=0, help_text='От 1 до 5', verbose_name='Рейтинг'),
        ),
    ]
