# Generated by Django 4.1.7 on 2023-03-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='author/', verbose_name='Фото')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('bio', models.CharField(max_length=200, verbose_name='Немного о себе')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Фейсбук')),
                ('google', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Гугл Почту')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Гугл Почту')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Гугл Почту')),
                ('pinteres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Гугл Почту')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs', verbose_name='Фото')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('create_add', models.DateField(auto_now_add=True, verbose_name='Время добавление')),
                ('description', models.TextField(verbose_name='Описание')),
                ('my_comment', models.TextField(blank=True, null=True, verbose_name='Мои комментарии')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.authorblog', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ReviewBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил')),
                ('message', models.TextField(max_length=500, verbose_name='Отвыз')),
                ('create_add', models.DateField(auto_now_add=True, verbose_name='Добавление')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='blogs.categoryblog', verbose_name='Категории'),
        ),
    ]
