# Generated by Django 4.1.7 on 2023-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='backgroung',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/back/', verbose_name='Фото для заднего фона'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs/', verbose_name='Фото'),
        ),
    ]
