# Generated by Django 4.1.7 on 2023-03-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0010_delete_bookingformpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил')),
                ('confirm_email', models.EmailField(max_length=254, verbose_name='Подтверджение Емаила')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('name_on_card', models.CharField(max_length=40, verbose_name='Имя на карте')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('expiration_date', models.CharField(max_length=5, verbose_name='Месяц / Год')),
                ('year', models.CharField(max_length=4, verbose_name='Год получения')),
                ('ccv', models.CharField(max_length=3, verbose_name='CCV')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
    ]
