# Generated by Django 4.1.7 on 2023-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cart_item',
            field=models.ManyToManyField(blank=True, related_name='cart_item_booking', to='cartitems.cartitem'),
        ),
    ]
