# Generated by Django 4.1.7 on 2023-06-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_alter_country_options_package_destination'),
        ('booking', '0002_booking_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
    ]
