# Generated by Django 4.1.7 on 2023-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='who',
            field=models.CharField(choices=[('Путешественник', 'Путешественник'), ('Турист', 'Турист')], max_length=14, verbose_name='Кто вы'),
        ),
    ]
